/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;

public class App {
    public static ArrayList<StarWarsQuotes> stars = new ArrayList<>();
    public static void main(String[] args) throws IOException {
        try {
            //Ron Swanson Quotes: https://ron-swanson-quotes.herokuapp.com/v2/quotes
            URL url = new URL("http://swquotesapi.digitaljedi.dk/api/SWQuote/RandomStarWarsQuote");
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");

            BufferedReader input = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String oneLine = input.readLine();
            StringBuilder entireStringResponse = new StringBuilder();
            while (oneLine != null) {
                entireStringResponse.append(oneLine);
                oneLine = input.readLine();
            }
            input.close();
            String starQuote = entireStringResponse.toString();

            Gson gUnit = new Gson();
            StarWarsQuotes vader = gUnit.fromJson(starQuote, StarWarsQuotes.class);
            stars.add(vader);
            System.out.println(vader.starWarsQuote);

            File internetQuote = new File("src/main/resources/internetQuote.json");

            if (!internetQuote.exists()) {
                internetQuote.createNewFile();
            }
            FileWriter dataFileWriter = new FileWriter("src/main/resources/internetQuote.json",
                    true);
            BufferedWriter buff = new BufferedWriter(dataFileWriter);
            buff.write("vader");
            gUnit.toJson(vader, dataFileWriter);
            buff.close();
            dataFileWriter.close();
        }
        catch(Exception e) {
            Gson gson = new Gson();
            RecentQuotes quotes = new RecentQuotes("Charles Dickens", "Hello?");
            Reader quoteReader = Files.newBufferedReader(Paths.get("src/main/resources/recentQuotes.json"));
            RecentQuotes[] numQuotes = gson.fromJson(quoteReader, RecentQuotes[].class);
            System.out.println(quotes.toString(getRandomNumber(0, 138), numQuotes));
        }

    }

    public static int getRandomNumber(int min, int max) {
        return (int) ((Math.random() * (max - min)) + min);
    }

}
